pragma Singleton

import QtQuick

QtObject {
    property color primary: "#82d3e0"
    property color on_primary: "#00363d"
    property color primary_container: "#004f58"
    property color on_primary_container: "#9eeffd"
    property color inverse_primary: "#006874"
    property color primary_fixed: "#9eeffd"
    property color primary_fixed_dim: "#82d3e0"
    property color on_primary_fixed: "#001f24"
    property color on_primary_fixed_variant: "#004f58"
    property color secondary: "#b1cbd0"
    property color on_secondary: "#1c3438"
    property color secondary_container: "#334b4f"
    property color on_secondary_container: "#cde7ec"
    property color secondary_fixed: "#cde7ec"
    property color secondary_fixed_dim: "#b1cbd0"
    property color on_secondary_fixed: "#051f23"
    property color on_secondary_fixed_variant: "#334b4f"
    property color tertiary: "#bac6ea"
    property color on_tertiary: "#24304d"
    property color tertiary_container: "#3b4664"
    property color on_tertiary_container: "#dae2ff"
    property color tertiary_fixed: "#dae2ff"
    property color tertiary_fixed_dim: "#bac6ea"
    property color on_tertiary_fixed: "#0e1b37"
    property color on_tertiary_fixed_variant: "#3b4664"
    property color error: "#ffb4ab"
    property color on_error: "#690005"
    property color error_container: "#93000a"
    property color on_error_container: "#ffdad6"
    property color surface_dim: "#0e1415"
    property color surface: "#0e1415"
    property color surface_tint: "#82d3e0"
    property color surface_bright: "#343a3b"
    property color surface_container_lowest: "#090f10"
    property color surface_container_low: "#171d1e"
    property color surface_container: "#1b2122"
    property color surface_container_high: "#252b2c"
    property color surface_container_highest: "#303637"
    property color on_surface: "#dee3e5"
    property color on_surface_variant: "#bfc8ca"
    property color outline: "#899294"
    property color outline_variant: "#3f484a"
    property color inverse_surface: "#dee3e5"
    property color inverse_on_surface: "#2b3133"
    property color surface_variant: "#3f484a"
    property color background: "#0e1415"
    property color on_background: "#dee3e5"
    property color shadow: "#000000"
    property color scrim: "#000000"
    property color source_color: "#232323"
}
