pragma Singleton

import QtQuick

QtObject {
    property color primary: "#ffb59b"
    property color on_primary: "#55200a"
    property color primary_container: "#72351e"
    property color on_primary_container: "#ffdbcf"
    property color inverse_primary: "#8f4c33"
    property color primary_fixed: "#ffdbcf"
    property color primary_fixed_dim: "#ffb59b"
    property color on_primary_fixed: "#380d00"
    property color on_primary_fixed_variant: "#72351e"
    property color secondary: "#e7bdb0"
    property color on_secondary: "#442a21"
    property color secondary_container: "#5d4036"
    property color on_secondary_container: "#ffdbcf"
    property color secondary_fixed: "#ffdbcf"
    property color secondary_fixed_dim: "#e7bdb0"
    property color on_secondary_fixed: "#2c160d"
    property color on_secondary_fixed_variant: "#5d4036"
    property color tertiary: "#d5c68e"
    property color on_tertiary: "#393005"
    property color tertiary_container: "#50461a"
    property color on_tertiary_container: "#f2e2a7"
    property color tertiary_fixed: "#f2e2a7"
    property color tertiary_fixed_dim: "#d5c68e"
    property color on_tertiary_fixed: "#221b00"
    property color on_tertiary_fixed_variant: "#50461a"
    property color error: "#ffb4ab"
    property color on_error: "#690005"
    property color error_container: "#93000a"
    property color on_error_container: "#ffdad6"
    property color surface_dim: "#1a110e"
    property color surface: "#1a110e"
    property color surface_tint: "#ffb59b"
    property color surface_bright: "#423733"
    property color surface_container_lowest: "#140c0a"
    property color surface_container_low: "#231a16"
    property color surface_container: "#271d1a"
    property color surface_container_high: "#322824"
    property color surface_container_highest: "#3d322f"
    property color on_surface: "#f1dfd9"
    property color on_surface_variant: "#d8c2bb"
    property color outline: "#a08d86"
    property color outline_variant: "#53433e"
    property color inverse_surface: "#f1dfd9"
    property color inverse_on_surface: "#392e2b"
    property color surface_variant: "#53433e"
    property color background: "#1a110e"
    property color on_background: "#f1dfd9"
    property color shadow: "#000000"
    property color scrim: "#000000"
    property color source_color: "#422216"
}
