pragma Singleton

import QtQuick

QtObject {
    property color primary: "#93cdf6"
    property color on_primary: "#00344c"
    property color primary_container: "#004c6d"
    property color on_primary_container: "#c7e7ff"
    property color inverse_primary: "#236488"
    property color primary_fixed: "#c7e7ff"
    property color primary_fixed_dim: "#93cdf6"
    property color on_primary_fixed: "#001e2e"
    property color on_primary_fixed_variant: "#004c6d"
    property color secondary: "#b6c9d8"
    property color on_secondary: "#21323e"
    property color secondary_container: "#384956"
    property color on_secondary_container: "#d2e5f5"
    property color secondary_fixed: "#d2e5f5"
    property color secondary_fixed_dim: "#b6c9d8"
    property color on_secondary_fixed: "#0b1d29"
    property color on_secondary_fixed_variant: "#384956"
    property color tertiary: "#cdc0e9"
    property color on_tertiary: "#342b4b"
    property color tertiary_container: "#4b4263"
    property color on_tertiary_container: "#e9ddff"
    property color tertiary_fixed: "#e9ddff"
    property color tertiary_fixed_dim: "#cdc0e9"
    property color on_tertiary_fixed: "#1f1635"
    property color on_tertiary_fixed_variant: "#4b4263"
    property color error: "#ffb4ab"
    property color on_error: "#690005"
    property color error_container: "#93000a"
    property color on_error_container: "#ffdad6"
    property color surface_dim: "#101417"
    property color surface: "#101417"
    property color surface_tint: "#93cdf6"
    property color surface_bright: "#353a3d"
    property color surface_container_lowest: "#0a0f12"
    property color surface_container_low: "#181c20"
    property color surface_container: "#1c2024"
    property color surface_container_high: "#262a2e"
    property color surface_container_highest: "#313539"
    property color on_surface: "#dfe3e7"
    property color on_surface_variant: "#c1c7ce"
    property color outline: "#8b9198"
    property color outline_variant: "#41484d"
    property color inverse_surface: "#dfe3e7"
    property color inverse_on_surface: "#2d3135"
    property color surface_variant: "#41484d"
    property color background: "#101417"
    property color on_background: "#dfe3e7"
    property color shadow: "#000000"
    property color scrim: "#000000"
    property color source_color: "#0b4967"
}
