pragma Singleton

import QtQuick

QtObject {
    property color primary: "#b8c3ff"
    property color on_primary: "#202c61"
    property color primary_container: "#374379"
    property color on_primary_container: "#dde1ff"
    property color inverse_primary: "#4f5b92"
    property color primary_fixed: "#dde1ff"
    property color primary_fixed_dim: "#b8c3ff"
    property color on_primary_fixed: "#07164b"
    property color on_primary_fixed_variant: "#374379"
    property color secondary: "#c3c5dd"
    property color on_secondary: "#2c2f42"
    property color secondary_container: "#424659"
    property color on_secondary_container: "#dfe1f9"
    property color secondary_fixed: "#dfe1f9"
    property color secondary_fixed_dim: "#c3c5dd"
    property color on_secondary_fixed: "#171b2c"
    property color on_secondary_fixed_variant: "#424659"
    property color tertiary: "#e4bad9"
    property color on_tertiary: "#44273e"
    property color tertiary_container: "#5c3d56"
    property color on_tertiary_container: "#ffd7f3"
    property color tertiary_fixed: "#ffd7f3"
    property color tertiary_fixed_dim: "#e4bad9"
    property color on_tertiary_fixed: "#2c1229"
    property color on_tertiary_fixed_variant: "#5c3d56"
    property color error: "#ffb4ab"
    property color on_error: "#690005"
    property color error_container: "#93000a"
    property color on_error_container: "#ffdad6"
    property color surface_dim: "#121318"
    property color surface: "#121318"
    property color surface_tint: "#b8c3ff"
    property color surface_bright: "#38393f"
    property color surface_container_lowest: "#0d0e13"
    property color surface_container_low: "#1b1b21"
    property color surface_container: "#1f1f25"
    property color surface_container_high: "#292a2f"
    property color surface_container_highest: "#34343a"
    property color on_surface: "#e3e1e9"
    property color on_surface_variant: "#c6c5d0"
    property color outline: "#90909a"
    property color outline_variant: "#45464f"
    property color inverse_surface: "#e3e1e9"
    property color inverse_on_surface: "#303036"
    property color surface_variant: "#45464f"
    property color background: "#121318"
    property color on_background: "#e3e1e9"
    property color shadow: "#000000"
    property color scrim: "#000000"
    property color source_color: "#606ba0"
}
