pragma Singleton

import QtQuick

QtObject {
    property color primary: "#ffb596"
    property color on_primary: "#552106"
    property color primary_container: "#71361a"
    property color on_primary_container: "#ffdbcd"
    property color inverse_primary: "#8e4d2f"
    property color primary_fixed: "#ffdbcd"
    property color primary_fixed_dim: "#ffb596"
    property color on_primary_fixed: "#360f00"
    property color on_primary_fixed_variant: "#71361a"
    property color secondary: "#e6beae"
    property color on_secondary: "#442a1f"
    property color secondary_container: "#5d4034"
    property color on_secondary_container: "#ffdbcd"
    property color secondary_fixed: "#ffdbcd"
    property color secondary_fixed_dim: "#e6beae"
    property color on_secondary_fixed: "#2c160c"
    property color on_secondary_fixed_variant: "#5d4034"
    property color tertiary: "#d2c78f"
    property color on_tertiary: "#373106"
    property color tertiary_container: "#4e471b"
    property color on_tertiary_container: "#efe3a9"
    property color tertiary_fixed: "#efe3a9"
    property color tertiary_fixed_dim: "#d2c78f"
    property color on_tertiary_fixed: "#201c00"
    property color on_tertiary_fixed_variant: "#4e471b"
    property color error: "#ffb4ab"
    property color on_error: "#690005"
    property color error_container: "#93000a"
    property color on_error_container: "#ffdad6"
    property color surface_dim: "#1a110e"
    property color surface: "#1a110e"
    property color surface_tint: "#ffb596"
    property color surface_bright: "#423733"
    property color surface_container_lowest: "#140c09"
    property color surface_container_low: "#231a16"
    property color surface_container: "#271e1a"
    property color surface_container_high: "#322824"
    property color surface_container_highest: "#3d322e"
    property color on_surface: "#f1dfd9"
    property color on_surface_variant: "#d8c2ba"
    property color outline: "#a08d85"
    property color outline_variant: "#53443e"
    property color inverse_surface: "#f1dfd9"
    property color inverse_on_surface: "#382e2a"
    property color surface_variant: "#53443e"
    property color background: "#1a110e"
    property color on_background: "#f1dfd9"
    property color shadow: "#000000"
    property color scrim: "#000000"
    property color source_color: "#ea6f33"
}
