
# Floating windows
windowrule {
    name = file-picker
    match:float = true

    float = on
    size = 900 600
    center = on
}

windowrule {
    name = python
    match:class = python3

    float = on
    size = 900 600
    center = on
}
