
# ─────────────────────────────────────────────────────────
#                         General
# ─────────────────────────────────────────────────────────
gappih=2
gappiv=2
gappoh=4
gappov=4
borderpx=0

# ─────────────────────────────────────────────────────────
#                       Decorations
# ─────────────────────────────────────────────────────────
border_radius=16
blur=0
shadows=0
animations=0

# ─────────────────────────────────────────────────────────
#                          Input
# ─────────────────────────────────────────────────────────
xkb_rules_layout=it
sloppyfocus=1
trackpad_natural_scrolling=1
warpcursor=1

# ─────────────────────────────────────────────────────────
#                         Layout
# ─────────────────────────────────────────────────────────
tagrule=id:1,layout_name:dwindle
tagrule=id:2,layout_name:dwindle
tagrule=id:3,layout_name:dwindle
tagrule=id:4,layout_name:dwindle
tagrule=id:5,layout_name:dwindle
tagrule=id:6,layout_name:dwindle
tagrule=id:7,layout_name:dwindle
tagrule=id:8,layout_name:dwindle
tagrule=id:9,layout_name:dwindle

dwindle_preserve_split=1
dwindle_hsplit=0
dwindle_vsplit=0
