

#          ╭──────────────────────────────────────────────────────────╮
#          │                         General                          │
#          ╰──────────────────────────────────────────────────────────╯

bind=SUPER,M,spawn,dms ipc call spotlight toggle
bind=SUPER+SHIFT,Return,quit
bind=SUPER,r,reload_config


#          ╭──────────────────────────────────────────────────────────╮
#          │                           Apps                           │
#          ╰──────────────────────────────────────────────────────────╯

bind=SUPER,Return,spawn,kitty -1
bind=SUPER,B,spawn,zen-browser


#          ╭──────────────────────────────────────────────────────────╮
#          │                      Window Actions                      │
#          ╰──────────────────────────────────────────────────────────╯

bind=SUPER,Q,killclient
bind=SUPER+SHIFT,Q,killclient,force
bind=SUPER,F,togglefloating

bind=SUPER,left,focusdir,left
bind=SUPER,right,focusdir,right
bind=SUPER,up,focusdir,up
bind=SUPER,down,focusdir,down

bind=SUPER+ALT,left,resizewin,-40,0
bind=SUPER+ALT,right,resizewin,40,0
bind=SUPER+ALT,up,resizewin,0,-40
bind=SUPER+ALT,down,resizewin,0,40

#          ╭──────────────────────────────────────────────────────────╮
#          │                        Workspaces                        │
#          ╰──────────────────────────────────────────────────────────╯

bind=SUPER,1,view,1
bind=SUPER,2,view,2
bind=SUPER,3,view,3
bind=SUPER,4,view,4
bind=SUPER,5,view,5
bind=SUPER,6,view,6
bind=SUPER,7,view,7
bind=SUPER,8,view,8
bind=SUPER,9,view,9
bind=SUPER,0,view,0

bind=SUPER+SHIFT,1,tag,1
bind=SUPER+SHIFT,2,tag,2
bind=SUPER+SHIFT,3,tag,3
bind=SUPER+SHIFT,4,tag,4
bind=SUPER+SHIFT,5,tag,5
bind=SUPER+SHIFT,6,tag,6
bind=SUPER+SHIFT,7,tag,7
bind=SUPER+SHIFT,8,tag,8
bind=SUPER+SHIFT,9,tag,9
bind=SUPER+SHIFT,0,tag,0

#          ╭──────────────────────────────────────────────────────────╮
#          │                       System Keys                        │
#          ╰──────────────────────────────────────────────────────────╯

bind=SUPER+SHIFT,S,spawn,systemctl suspend

bindl=NONE,XF86AudioRaiseVolume,spawn,wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+
bindl=NONE,XF86AudioLowerVolume,spawn,wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bindl=NONE,XF86AudioMute,spawn,wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bindl=NONE,XF86AudioMicMute,spawn,wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle
bindl=NONE,XF86MonBrightnessUp,spawn,brightnessctl -e4 -n2 set 5%+
bindl=NONE,XF86MonBrightnessDown,spawn,brightnessctl -e4 -n2 set 5%-

bindl=NONE,XF86AudioNext,spawn,playerctl next
bindl=NONE,XF86AudioPause,spawn,playerctl play-pause
bindl=NONE,XF86AudioPlay,spawn,playerctl play-pause
bindl=NONE,XF86AudioPrev,spawn,playerctl previous
